name: fvapp
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

  #------------------- PACKAGES --------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Package
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  shimmer: ^3.0.0
  url_launcher: ^6.3.0
  midtrans_sdk: ^0.4.0
  connectivity_plus: ^5.0.1
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0
  table_calendar: ^3.0.9
  pdf: ^3.10.8
  path_provider: ^2.1.3
  webview_flutter: ^4.8.0
  
  open_file: ^3.3.2
  printing: ^5.13.1
  image_picker: ^1.1.2
  video_player: ^2.8.7
  chewie: ^1.8.1
  # device_info_plus: ^10.1.0
  multiple_images_picker: ^1.0.1
  flutter_launcher_icons: ^0.13.1
  cached_network_image: ^3.3.1
  file_picker: ^8.0.6

  # package_info_plus: ^8.0.0

  
  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  flutter_image_compress: ^2.3.0

  # Firebase
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.0
  firebase_app_check: ^0.2.2+7
  cloud_firestore: ^4.13.1
  google_sign_in: ^6.1.6
  firebase_database: ^10.5.3
  firebase_storage: ^11.7.6
  uuid: ^4.4.0
  flutter_inappwebview: ^6.0.0

  #------------------- PACKAGE END --------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^10.2.1
  dio: ^4.0.6
  rating_dialog: ^2.0.4
  shared_preferences: ^2.0.15
  provider: ^6.0.4

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
    
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/mylogo.png"

flutter:

  uses-material-design: true

  
  assets:
    - assets/logos/mylogo.png
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/user/
    - assets/images/reviews/
    - assets/logos/
    - assets/icons/
    - assets/icons/admin_icons/
    - assets/icons/categories/
    - assets/icons/brands/
    - assets/icons/payment_methods/

  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
