name: fvapp
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

  #------------------- PACKAGES --------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Package
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0
  
  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1

  #------------------- PACKAGE END --------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^10.2.1
  table_calendar: ^3.0.8
  lottie: ^2.0.0
  dio: ^4.0.6
  rating_dialog: ^2.0.4
  shared_preferences: ^2.0.15
  provider: ^6.0.4

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  
  assets:
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/user/
    - assets/images/reviews/
    - assets/logos/
    - assets/icons/
    - assets/icons/categories/
    - assets/icons/brands/

  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
