// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-L5AN-JWCqy0rWiumJKwRxfQcYl8b-CM',
    appId: '1:958277585930:web:2b0332f3fa09de2b8da3f3',
    messagingSenderId: '958277585930',
    projectId: 'fvapplication-3bf28',
    authDomain: 'fvapplication-3bf28.firebaseapp.com',
    storageBucket: 'fvapplication-3bf28.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp9nY-XAfmzluUVj8iCcUsvE9UhTMb7f0',
    appId: '1:958277585930:android:047a1b5d0f768e6a8da3f3',
    messagingSenderId: '958277585930',
    projectId: 'fvapplication-3bf28',
    storageBucket: 'fvapplication-3bf28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmzLfg81_ABXEzkdnau-5kxLhI4k7pgX8',
    appId: '1:958277585930:ios:8f5dbda84f3b96ff8da3f3',
    messagingSenderId: '958277585930',
    projectId: 'fvapplication-3bf28',
    storageBucket: 'fvapplication-3bf28.appspot.com',
    androidClientId: '958277585930-ac5on0jf5t4rbn1r10du8paovhr4ors7.apps.googleusercontent.com',
    iosClientId: '958277585930-vm48569ng4hlb9bqmsd7h3rcacnpg5rj.apps.googleusercontent.com',
    iosBundleId: 'com.example.fvapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmzLfg81_ABXEzkdnau-5kxLhI4k7pgX8',
    appId: '1:958277585930:ios:540a38186a058b468da3f3',
    messagingSenderId: '958277585930',
    projectId: 'fvapplication-3bf28',
    storageBucket: 'fvapplication-3bf28.appspot.com',
    androidClientId: '958277585930-ac5on0jf5t4rbn1r10du8paovhr4ors7.apps.googleusercontent.com',
    iosClientId: '958277585930-alm0tt9ko9g3k0173m0r12mrqq2j2duu.apps.googleusercontent.com',
    iosBundleId: 'com.example.fvapp.RunnerTests',
  );
}
